### ISSUE TITLE
Batch/cmd file icon proposal

### ISSUE THREAD

**Issue by ilepn** [LaurentTreguier/vscode-simple-icons#10]
Hi and thanks for great set of icons!

However, currently batch/cmd files are somewhat hard to distinguish rapidly from other grayish icons. Therefore, I'd suggest that the icon for this type of files could be e.g. same as PowerShell but with black background color instead of blue and maybe having same text inside the icon as standard windows 7 cmd icon: "C:\ _" or "CMD"?

Best regards,
IL

**Comment by LaurentTreguier** [comment]
When I started working on this theme, I had some kind of bug when overriding icons for light themes, which is why these icons are grey : it works for both light and dark themes. However, I just tested again and it looks like the bug has been solved since then, so I'll happily make the CMD icon black/white for light/dark themes.

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/23861803/769a994a-080b-11e7-86ea-5a6e87464ab5.png)
![image](https://cloud.githubusercontent.com/assets/7602755/23861819/835ae34c-080b-11e7-9d5e-90dc6db48c85.png)

**Comment by ilepn** [comment]
These look definitely more clear than the current ones! However, what I had
in mind was kind of replacing the icon with something that could be similar
to Powershell icon but in white and black.. or just something that really
looks like the cmd window itself, that would be awesome! I have just
snipped few examples below of what I had in mind, if there anything
considerable in design. Thanks tho for the super fast answer and solution
already! 👍

[image: Tekstiin lisättävä kuva 2]

2017-03-13 17:39 GMT+02:00 LaurentTreguier <notifications@github.com>:

**Comment by LaurentTreguier** [comment]
I think the image wasn't uploaded correctly, all I see is `[image: Tekstiin lisättävä kuva 2]`

**Comment by ilepn** [comment]
Thanks for noting about this! It might be because I pasted the image from
clipboard. I hope you could see the examples now, as I've attached them
"the normal way". These icons are not created by me, I've just picked them
up from Windows OS / internet to show what I'm thinking.

2017-03-14 9:23 GMT+02:00 LaurentTreguier <notifications@github.com>:

**Comment by LaurentTreguier** [comment]
Have you edited your comment ? I still don't see any images 😕

**Comment by ilepn** [comment]
That's weird! I have edited and this time I attached the images in the
message the traditional way. Let me store these in my GDrive, see the links
below:

https://drive.google.com/file/d/0B_-fZGouhvMcTlZPaV96MHhTdGJscjBXdWVUY3FJUlNyUXhB/view?usp=sharing
https://drive.google.com/file/d/0B_-fZGouhvMccjhOejJ1SlVScVBRaWFfQVAwZTRobGRqYlFZ/view?usp=sharing
https://drive.google.com/file/d/0B_-fZGouhvMcYWVnMjNkSDk0TnB5UlZLYnNCNTVGVFFyZllN/view?usp=sharing

2017-03-14 20:37 GMT+02:00 LaurentTreguier <notifications@github.com>:

**Comment by LaurentTreguier** [comment]
Okay, now I can see them alright, I'll see what I can make up

**Comment by ilepn** [comment]
Great! Looking forward to hearing about it! 😉

2017-03-14 21:00 GMT+02:00 LaurentTreguier <notifications@github.com>:

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/23919410/0cccb13c-08f7-11e7-99a3-f489e130b32c.png)
![image](https://cloud.githubusercontent.com/assets/7602755/23919417/116c7614-08f7-11e7-83fc-103fe4fc58ee.png)

**Comment by ilepn** [comment]
Amazing work, thank you! Those are now looking much distinguishable
compared to previous ones! Are you going to implement those?

**Comment by LaurentTreguier** [comment]
If that satisfies you, then yes ; I think I'll also make the shellscript icons like this, with the `>_` instead of `C:\` and the pixels for the window control buttons on the left side instead of the right side

**Comment by LaurentTreguier** [comment]
I still have a question :
![image](https://cloud.githubusercontent.com/assets/7602755/23939567/989749a6-0961-11e7-9a0a-7486f6f267eb.png)
Is it better with or without transparency ? (it might be hard to compare the two against Github's white background though)

**Comment by ilepn** [comment]
I somehow like the one on the bottom (a.sh). For me it's sharpest looking
and therefore fast and easy to recognize.

2017-03-15 10:32 GMT+02:00 LaurentTreguier <notifications@github.com>:

**Comment by LaurentTreguier** [comment]
I have to say I feel the same. I prefer having a plain icon rather than an overly transparent one.

**Comment by LaurentTreguier** [comment]
Closed by ad2b07b2b248aad6fca7e0b3a8feb7544986268f and 4a58e14ebbd05968dc18d271b48028aee4122d78
