### ISSUE TITLE
Spec File Icons

### ISSUE THREAD

**Issue by premranderia** [LaurentTreguier/vscode-simple-icons#11]
Can we have a different icons for a spec.js files vs js files ?

**Comment by LaurentTreguier** [comment]
Sure. I'll try some things, don't hesitate to post ideas if you have any

**Comment by LaurentTreguier** [comment]
Here is some mix of the javascript icon and the test folder icon :
![image](https://cloud.githubusercontent.com/assets/7602755/24002126/3fc834d4-0a60-11e7-811b-d6cfb98cb6e5.png)
However I don't know if that's distinguishable enough.
