### ISSUE TITLE
Missing icon for REG (reg) files

### ISSUE THREAD

**Issue by ilepn** [LaurentTreguier/vscode-simple-icons#12]
Hi again!

I've noticed that Windows registry files, REG (reg), are not supported. Do you have time / are you able to sketch something appropriate?

Few images below (taken from Windows (regedit) and icons8, to propose examples:

![image](https://cloud.githubusercontent.com/assets/26382655/24237604/ac7dd3f0-0faf-11e7-881b-7011062ab9de.png)

![image](https://cloud.githubusercontent.com/assets/26382655/24237555/711b243e-0faf-11e7-8e9e-9fb873d38f73.png)

Best regards,
K

**Comment by LaurentTreguier** [comment]
Sure

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/24239323/cf8c38e8-0fad-11e7-8bad-3d50a99c4020.png)

**Comment by ilepn** [comment]
That is looking really good! I'm just re-thinking about going to Windows 10 direction as this 3D-kind of icon could actually be nicer..  What do you think about the image below? (Sorry that I hadn't this attached at first place!)

![image](https://cloud.githubusercontent.com/assets/26382655/24240858/b7a26b86-0fbb-11e7-8612-2e0e9a9be93e.png)

**Comment by LaurentTreguier** [comment]
I made a quick test with a 2x2x2 sized cube (since the rendered icon is small):
![image](https://cloud.githubusercontent.com/assets/7602755/24244830/cb37a274-0fc0-11e7-96d3-8f0a6ee7420e.png)
EDIT:
here is a less "squashed" version:
![image](https://cloud.githubusercontent.com/assets/7602755/24245215/352af194-0fc2-11e7-92a4-7a96126bc6ed.png)

**Comment by ilepn** [comment]
Now that is looking gorgeous! Let's go with this one? :+1:

**Comment by LaurentTreguier** [comment]
I'll make an SVG and push an update (the test was a PNG)

**Comment by ilepn** [comment]
Great work, many thanks! :)
