### ISSUE TITLE
Please provide an icon for .vue file

### ISSUE THREAD

**Issue by liuyuchenzh** [LaurentTreguier/vscode-simple-icons#14]
![image](https://cloud.githubusercontent.com/assets/12220475/24387256/a5b56538-13a6-11e7-863d-6c3643639f9e.png)
An icon for .vue file would be nice.

**Comment by LaurentTreguier** [comment]
Do you have [an extension that provides support for Vue files](https://marketplace.visualstudio.com/items?itemName=jcbuisson.vue) ? You should be able to see icons for Vue files as long as you have one.

**Comment by liuyuchenzh** [comment]
My bad. It actually works.
![image](https://cloud.githubusercontent.com/assets/12220475/24402401/fb1b1c18-13ea-11e7-8282-59b7acbb18dd.png)
Thanks for your awesome work!
PS: I'm using [this extension](https://marketplace.visualstudio.com/items?itemName=hollowtree.vue-snippets)
