### ISSUE TITLE
Babel and csscomb

### ISSUE THREAD

**Issue by osawasatoru** [LaurentTreguier/vscode-simple-icons#15]
Please add  icons for the extension '.babelrc' and '.csscomb.json'.

**Comment by LaurentTreguier** [comment]
I'll see to it. There might be some time before the next version is released though

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/24644591/b6dbcab4-1914-11e7-8706-10c16a786ae8.png)
EDIT: the csscomb icon seemed a bit too dark to me
![image](https://cloud.githubusercontent.com/assets/7602755/24644993/a34c5a48-1916-11e7-8518-1580a3909017.png)

**Comment by osawasatoru** [comment]
It’s all good :eyes:

Thank you for quick response!
