### ISSUE TITLE
EJS icon

### ISSUE THREAD

**Issue by mkvlrn-cm42** [LaurentTreguier/vscode-simple-icons#16]
Any chance of adding a .ejs icon in the future?

Just needed a single EJS (http://www.embeddedjs.com/) file to template something with html-webpack-loader and, to my complete horror, there was no icon!

Thanks. :)

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/24662905/c5f8a73c-1956-11e7-90f5-95bfc46e6cb8.png)
Here is a first try along with other javascript icons

**Comment by mkvlrn-cm42** [comment]
Oh, this is perfect!
