### ISSUE TITLE
favicon.*

### ISSUE THREAD

**Issue by yaphtes** [LaurentTreguier/vscode-simple-icons#17]
Hello, can you add specific icon for favicon.*

**Comment by LaurentTreguier** [comment]
For now I have no idea for making a specific icon for this, but I'll try to come up with something

**Comment by yaphtes** [comment]
Maybe [this](https://www.iconfinder.com/icons/1398915/favorite_five_point_gold_star_icon#size=128)?

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/24830223/a107de24-1c81-11e7-8cfd-e3326c28004b.png)
Unfortunately it looks like iconfinder.com's security certificate expired a few hours ago, and I can't get a look

**Comment by yaphtes** [comment]
![1491684074_star_gold](https://cloud.githubusercontent.com/assets/16673624/24830268/846ac8fa-1c93-11e7-8f14-4ebfa5bbb4f2.png)

**Comment by LaurentTreguier** [comment]
Here are some icons:
![image](https://cloud.githubusercontent.com/assets/7602755/24830484/6b3dbc2c-1c87-11e7-9153-1a8c4064a5e6.png)
![image](https://cloud.githubusercontent.com/assets/7602755/24830488/979934e0-1c87-11e7-8d95-16ffedc167ff.png)
![image](https://cloud.githubusercontent.com/assets/7602755/24830501/d1edf072-1c87-11e7-9053-6221ca472924.png)

**Comment by yaphtes** [comment]
I think the second is the most suitable.
You need to consider all the names of the favicon extensions, that is, the favicon.* [favicon.ico, favicon.png] etc

**Comment by LaurentTreguier** [comment]
I agree. I thought the first one could be interesting, but in the end it's not as simple and straightforward.

**Comment by yaphtes** [comment]
Yes, I'm the second option is more suitable. Because light themes do not fit well with the first.
