### ISSUE TITLE
Vue.js files don't show Vue icon

### ISSUE THREAD

**Issue by brandonk3nt** [LaurentTreguier/vscode-simple-icons#18]
Files with the `.vue` extension don't show their correct icon:

![screen shot 2017-04-07 at 6 38 57 am](https://cloud.githubusercontent.com/assets/10407384/24802472/fbf3f7bc-1b5c-11e7-9e3c-0d6a5c2ddd83.png)

**Comment by LaurentTreguier** [comment]
Do you have an extension that provides support for Vue files ? Like [this one](https://marketplace.visualstudio.com/items?itemName=jcbuisson.vue)

**Comment by Wizard-of-AZ** [comment]
just installed and that fixed it, thanks!
