### ISSUE TITLE
Please add a visualforce icon

### ISSUE THREAD

**Issue by ghost** [LaurentTreguier/vscode-simple-icons#20]
Hey, I like your extension since it adds good icons for apex classes and triggers. Could you please add visualforce pages too?
This would complete the icon set for my salesforce development.

**Comment by LaurentTreguier** [comment]
Is something like this OK ?
![image](https://user-images.githubusercontent.com/7602755/27032750-c531116c-4f76-11e7-863e-22096a84a1df.png)
From what I looked up visualforce seems to be some kind of markup language
