### ISSUE TITLE
Icon for root folders

### ISSUE THREAD

**Issue by faustinoaq** [LaurentTreguier/vscode-simple-icons#24]
From VSCode [1.15 release](https://code.visualstudio.com/updates/v1_15#_icon-for-root-folders):

> Icon theme authors, please get ready for multi-root support: We added two new icon categories for VS Code: rootFolder and rootFolderExpanded that can be used to show root folders in a different way compared to other folders. For example, the File Explorer will use this icon as well as the list of recently opened workspaces.

![1_15_root_icon](https://user-images.githubusercontent.com/3067335/29202003-d30ecef2-7e31-11e7-8af1-7ba22644cf2d.png)

**Comment by LaurentTreguier** [comment]
I read the release notes too quickly and didn't see that... I'll read it more thoroughly next time. Next update will have those (and it will come soon enough).
