### ISSUE TITLE
Add icons to default types

### ISSUE THREAD

**Issue by faustinoaq** [LaurentTreguier/vscode-simple-icons#29]
Hi @LaurentTreguier 

This time I'm here to bring an idea about creating icons for default filetypes supported by VSCode it's almost done, except by:

- [x] Git commit file:

![screenshot_20171114_183701](https://user-images.githubusercontent.com/3067335/32810838-cff2fcf0-c96a-11e7-8e91-b6b63186804c.png)

- [x] [HLSL](https://es.wikipedia.org/wiki/High_Level_Shader_Language) High Level Shader Language

![screenshot_20171114_183901](https://user-images.githubusercontent.com/3067335/32810898-17928918-c96b-11e7-9c59-dc3c743e9fda.png)

- [x] [XSL](https://www.w3.org/Style/XSL/WhatIsXSL.html) XML styles-sheets 

![screenshot_20171114_184053](https://user-images.githubusercontent.com/3067335/32810952-5ab6d708-c96b-11e7-9cf4-e1d7606f36cb.png)
 
BTW, Thank you for blue icon again! 😄 

![screenshot_20171114_184454](https://user-images.githubusercontent.com/3067335/32811089-e9563328-c96b-11e7-8b90-78a940206d37.png)

**Comment by LaurentTreguier** [comment]
No problem for the blue icon, thank the VSCode team instead for going back to the blue icon with VSCode 1.18 instead of sticking with the weird orange one 😄
I'm going to have a look for making these icons, they shouldn't pose any problem.

**Comment by LaurentTreguier** [comment]
![image](https://user-images.githubusercontent.com/7602755/32841195-0569fdde-ca1a-11e7-9281-ec52db4f6a69.png)
Here is what I ended up with. Git commit and rebase messages are a git variant of the normal file icon (they are simply text files unless I'm mistaken). XSL files use the XML icon with the blue from the CSS icon, as they are essentially XML that provides styling. Finally, the HLSL files have a DirectX logo icon.

**Comment by faustinoaq** [comment]
Awesome! 😍
