### ISSUE TITLE
Can't see the folders/icons from 1.7.1 Release

### ISSUE THREAD

**Issue by leocaseiro** [LaurentTreguier/vscode-simple-icons#30]
VSCode Version 1.18.0 (1.18.0) 2017-11-08T12:28:16.811Z on macOS Sierra 10.12.16

I'm not sure if it's related to the `hidesExplorerArrows`, but for some reason, I can't see the folders anymore:

### vscode-simple-icons
<img width="302" alt="screen shot 2017-11-16 at 11 41 19 am" src="https://user-images.githubusercontent.com/940070/32867772-2de94efa-cac3-11e7-8131-57ee01aa87a3.png">

Where it should be similar to some other fonts:
### emmanuelbeziat.vscode-great-icons
<img width="224" alt="screen shot 2017-11-16 at 11 41 42 am" src="https://user-images.githubusercontent.com/940070/32867794-4b75bab2-cac3-11e7-9fea-d176b824d8f8.png">

> UPDATE: Actually, most of the icons are not working for me =/

**Comment by LaurentTreguier** [comment]
Weird... I can't reproduce this on Linux or Windows. Did the installation of the new version fail somehow ? can you look inside `~/.vscode/extensions/LaurentTreguier.vscode-simple-icons-1.7.1` (I assume this is where extensions are stored on macOS as well) to see what's in there ?

**Comment by leocaseiro** [comment]
Hi @LaurentTreguier, thanks you so much for your reply and help.

I've removed the folder at `~/.vscode/extensions/LaurentTreguier.vscode-simple-icons-1.7.1` and reinstalled the extension and it's working now!

Awesome!

Cheers!
