### ISSUE TITLE
Add an option to show arrow

### ISSUE THREAD

**Issue by Guema** [LaurentTreguier/vscode-simple-icons#32]
Hello,

I don't know if it is actually possible, or either desirable, but folder arrow felt useful for me.
Can you put a config flag or something else to let user choose between no arrow or yes arrow ?

Thanks for this nice plugin

Guema

**Comment by LaurentTreguier** [comment]
It should be possible. The [vscode-icons](https://github.com/vscode-icons/vscode-icons) extension allows changing the icons of the extension, in the same way I could probably toggle the arrows.

**Comment by LaurentTreguier** [comment]
I've gone for a configuration point for the extension instead. It seems more natural than a command, and since configuration is stored independently from the extension itself, the showing/hiding won't be reset when a new version of the extension comes out.

**Comment by Guema** [comment]
Working like a charm.
Thank you very much !
Keep this nice work !

Guema
