### ISSUE TITLE
Add support for .jekyll files

### ISSUE THREAD

**Issue by hacknug** [LaurentTreguier/vscode-simple-icons#36]
Jekyll Syntax Support add syntax highlighting to `.jekyll` files. It would be great if we could have an icon with the jekyll test tube logo: https://github.com/jekyll/brand

I can take a look at it and open a PR if you'd prefer that.

**Comment by LaurentTreguier** [comment]
|Dark theme|Light theme|
|---|---|
|![image](https://user-images.githubusercontent.com/7602755/39676214-2d9e47b8-5167-11e8-9a8b-b53250d1d618.png)|![image](https://user-images.githubusercontent.com/7602755/39676227-53c4428a-5167-11e8-94ab-9470faa46c51.png)|

This is what I have right now; simply the tiltes test tube. I was thinking about adding the gradient to the red part, but at this size I don't think it's going to be very visible.

**Comment by hacknug** [comment]
This is perfect! No need to add any details since they also use a simplified tube for smaller sizes.
