### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ghost** [LaurentTreguier/vscode-simple-icons#37]
?

**Comment by LaurentTreguier** [comment]
This reminds me of #30. Have you tried just removing `[YOUR HOME PATH]\.vscode\extensions\LaurentTreguier.vscode-simple-icons-1.8.3` and re-installing the extension ? This looks like a weird buggy  update.

**Comment by qawsqs** [comment]
I've tried to remove and re-install the extension via vs code and it didn't work.
Deleting the folder has helped.
