### ISSUE TITLE
Add support for posthtml.config.js and .posthtmlrc

### ISSUE THREAD

**Issue by hacknug** [LaurentTreguier/vscode-simple-icons#38]
This is just a config file for posthtml. The color should probably be this one which is the one they're using on their Twitter profile: `#FA743E`.

I think it might also be a good idea to use the default config icon for all files that end with `.config.js`.

**Comment by LaurentTreguier** [comment]
I can always try to reproduce the gradient. Do posthtml config files also have name variants like for postcss ?

**Comment by hacknug** [comment]
Yes but it's just the two on the title: https://github.com/posthtml/posthtml-load-config

**Comment by LaurentTreguier** [comment]
Ok. I'm on this and #39 when I can

**Comment by hacknug** [comment]
No rush. Just thought this would be a nice addition to the extension. Thank you!

**Comment by LaurentTreguier** [comment]
I'm not rushing, just pointing out I'll be working on this :+1:
