### ISSUE TITLE
Lua icon saturation

### ISSUE THREAD

**Issue by sjml** [LaurentTreguier/vscode-simple-icons#4]
The super-saturated blue on the Lua icons doesn't look great against the chrome when VS Code is in dark mode. Would you consider toning it down a bit? 

<img width="153" alt="screen shot 2017-01-13 at 10 35 35 am" src="https://cloud.githubusercontent.com/assets/1638331/21941114/20860958-d97c-11e6-92c1-d58df4635243.png">

Thanks for the great work on this set; I'm a big fan of the simplicity.

**Comment by LaurentTreguier** [comment]
I'm not a Lua coder so I didn't see the icon much after making, and yes it's not looking too great.
Is something like one of those better ?
![image](https://cloud.githubusercontent.com/assets/7602755/21941270/3882e6ba-d9c8-11e6-96fa-988de6d4cd62.png)
![image](https://cloud.githubusercontent.com/assets/7602755/21941316/7d89a92e-d9c8-11e6-8f3e-0f18aa0eae6e.png)

**Comment by sjml** [comment]
Of those two, I like the bottom one more. 👍

**Comment by sjml** [comment]
You could even think of matching the light blue of the text files, but I don't know if you're trying to have code files pop more.

**Comment by LaurentTreguier** [comment]
I think having different colors help distinguish file types better, so I think I won't match colors with text files. Anyway, I'll update the color in a moment. And I like the bottom one more too :)

**Comment by sjml** [comment]
Awesome! 😁
