### ISSUE TITLE
Racket icon

### ISSUE THREAD

**Issue by ghost** [LaurentTreguier/vscode-simple-icons#40]
is not here a racket icon for .rkt files?

**Comment by LaurentTreguier** [comment]
From http://www.racket-lang.org/, the icon looks very much like ![the scheme icon](https://github.com/LaurentTreguier/vscode-simple-icons/blob/master/source/simple-icons/scheme.svg). Is it ok if I simply link this to `.rkt` files ?

**Comment by ghost** [comment]
Ya sure :p
