### ISSUE TITLE
New Golang branding could make for better icon

### ISSUE THREAD

**Issue by sjml** [LaurentTreguier/vscode-simple-icons#49]
The little gopher is kinda hard to read, and they [have a new branding](https://blog.golang.org/go-brand) now, which might be worth adding?

**Comment by LaurentTreguier** [comment]
At some point I was thinking about changing the icon to just include the head of the gopher since the rest is so tiny, and forgot about it after a while.
Thanks for the info, I'll probably use this new icon

**Comment by LaurentTreguier** [comment]
I have ended up with this: ![golang](https://user-images.githubusercontent.com/7602755/52976381-99020400-33c9-11e9-9653-43d97c44cebc.png)

**Comment by sjml** [comment]
Looks good!
