### ISSUE TITLE
Suggestion: Change PHP file icons

### ISSUE THREAD

**Issue by alx-so** [LaurentTreguier/vscode-simple-icons#5]
It would be nice to have nice PHP icons ))

**Comment by LaurentTreguier** [comment]
Yes it would. But I haven't found any good idea to make better PHP icons...
Do you have any suggestion ?
EDIT : I just tried using the basic logo :
![image](https://cloud.githubusercontent.com/assets/7602755/21956490/86bd5f8a-da82-11e6-94bc-1e04fd4af034.png)

**Comment by alx-so** [comment]
Some icons from the web:
![icon-php](https://cloud.githubusercontent.com/assets/8975621/21963527/453dd3aa-db45-11e6-9392-5ae6766d4a21.png)
![icon-php2](https://cloud.githubusercontent.com/assets/8975621/21963528/453de624-db45-11e6-80f6-94baa97aa979.png)
![unnamed](https://cloud.githubusercontent.com/assets/8975621/21963529/453ec684-db45-11e6-87a8-1693be99ea0b.png)

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/21965330/19999266-db5e-11e6-9c51-f4667232e4f1.png)
More like this ?
I think I'll keep this color as it's the one from the [official logo](https://commons.wikimedia.org/wiki/File:PHP_Logo,_text_only.svg#/media/File:PHP-logo.svg)

**Comment by alx-so** [comment]
Maybe try to set text color white?

**Comment by LaurentTreguier** [comment]
![image](https://cloud.githubusercontent.com/assets/7602755/21977212/8b10cd0c-dbd5-11e6-8679-70237120e13a.png)
The earlier one was using transparent text, so it would appear white with a light theme and black with a dark theme

**Comment by alx-so** [comment]
Like your last one. For me white text looks more appealing)

You also have .html, .css, .sass icons with white text on it. Just checked with light color theme. Looks good)

**Comment by LaurentTreguier** [comment]
The reason these have white text is because the icons are made using the official logos (which use white text). The official PHP logo uses black text. However if you are using a light theme, then the transparent text version looks like this :
![image](https://cloud.githubusercontent.com/assets/7602755/21986112/5bb517ce-dbfe-11e6-891e-52d124326fb9.png)
![image](https://cloud.githubusercontent.com/assets/7602755/21986124/6aebf708-dbfe-11e6-8c7f-dc3c79bf35ad.png)

**Comment by alx-so** [comment]
OK, I got it about tranparency ) I just like the white text color on both light and dark theme )

Anyway, decision is up to you )
