### ISSUE TITLE
Add support for .svelte files

### ISSUE THREAD

**Issue by loilo** [LaurentTreguier/vscode-simple-icons#53]
[Svelte](https://svelte.dev) already has [a VS Code extension](https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode) but currently no icon.

The Svelte logo (can be found [here](https://github.com/sveltejs/branding/blob/master/svelte-logo.svg)) would probably make for a decent icon:

![Screenshot of three Svelte components with artificially inserted file icons](https://user-images.githubusercontent.com/1922624/57587911-ebf0e080-750c-11e9-8b30-971ef9cc03c1.png)

Would be awesome to see this added. 🙂

**Comment by LaurentTreguier** [comment]
Added in patch 1.11.7 :+1:
