### ISSUE TITLE
Registering a new syntax hilighting extension breaks icon theme?

### ISSUE THREAD

**Issue by jcklpe** [LaurentTreguier/vscode-simple-icons#56]
Hi. 

Love your icon theme! It's my favorite :D 

I am currently writing a small extension for myself, that basically modifies syntax highlighting for javascript, html etc. 

For some reason, when I register these new syntax grammars it breaks the icon theme and instead of showing the proper javascript or html icon it just shows a default gray blank document. 

## more detail. 
I originally tried to register these new grammars as injections rather than as new languages because that seemed the right way to do things. But I couldn't seem to get it to work properly. So instead I registered these syntax additions as "new" languages. 

This means that when I open an html file or whatever and I inspect it's TextMate theme scope it will say something like "text.hmtl" but it will also include a scope called "html.enzo". 

But it also means that for some reason the "example-file.html" isn't being registered by the icon theme as an html file, and therefore the html icon won't show up in the explorer. 

![image](https://user-images.githubusercontent.com/9451726/60775143-3db88000-a0e4-11e9-8af1-6b44a93b4a25.png)
![image](https://user-images.githubusercontent.com/9451726/60775146-490bab80-a0e4-11e9-9dc9-4d95634f0f54.png)
![image](https://user-images.githubusercontent.com/9451726/60775148-59bc2180-a0e4-11e9-99b5-5f2e6bc5e2a6.png)

![image](https://user-images.githubusercontent.com/9451726/60775158-722c3c00-a0e4-11e9-83aa-7dce3bb95fe9.png)

![image](https://user-images.githubusercontent.com/9451726/60775159-86703900-a0e4-11e9-92a0-c05a3d7ed5e9.png)

**Comment by LaurentTreguier** [comment]
This happens because `.html` and `.js` files are handled with language ids and not file extensions. Since with your extension, the `enzo` language id is now used for those files, VSCode tries to find Enzo icons for `.html` and `.js` files.
To solve this, I could explicitly always associate icons with file extensions.

**Comment by jcklpe** [comment]
@LaurentTreguier That would be a solution but it seems like I should probably come up with a better solution on my end so that my extension is more anti-fragile. 

I fixed things by figuring out how to get things to properly use injectTo anyway. 


Thanks!
