### ISSUE TITLE
Request - It will be great to add configuration for file.svg custom color

### ISSUE THREAD

**Issue by DNonov** [LaurentTreguier/vscode-simple-icons#58]
I'm a big fan of the theme. Color customization of the plain folders was a selling point for me. 

I think the theme will be even better if there is a configuration like "icons.file.color" related to the plain file's icon file.svg. So the user will have full control over the plain folder and file colors and will be able to match them.

Thank you very much for the work you put into the theme.

**Comment by LaurentTreguier** [comment]
The newest version (1.12.0) now has the same setting as the standard folder for the standard file icon!
