### ISSUE TITLE
Please publish the extension to Open VSX

### ISSUE THREAD

**Issue by eternal-sorrow** [LaurentTreguier/vscode-simple-icons#61]
Hi!

I'm a VS Code-OSS user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.

I want to request if it's possible to add the Simple Icons extension on the [open-vsx.org](https://open-vsx.org/) marketplace, because it's unclear if Microsoft marketplace is legal to use on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

Thanks.

**Comment by LaurentTreguier** [comment]
I didn't know this existed, I'll look into publishing it there. I do like the idea of having an open marketplace on top of using an open-source editor

**Comment by LaurentTreguier** [comment]
I've published a version 1.13.4: https://open-vsx.org/extension/LaurentTreguier/vscode-simple-icons
The namespace is not yet claimed however, so until then there is no guarantee that new versions of the extensions over there are published by me

**Comment by LaurentTreguier** [comment]
And now I've been granted the namespace I created :tada:
