### ISSUE TITLE
Suggestion: Add icons for .cshtml files

### ISSUE THREAD

**Issue by JaimeStill** [LaurentTreguier/vscode-simple-icons#9]
Currently, `.cshtml` files only show as gray documents.  This is the only oversight I've seen so far. Thanks for the great extension!  

![cshtml_icons](http://i.imgur.com/SYkFzHq.png)

**Comment by LaurentTreguier** [comment]
Hmmm... I'd be glad to add some icon, but it looks like there is no logo whatsoever for razor pages. I'll try to come up with something probably mixing the HTML and C# icons

**Comment by LaurentTreguier** [comment]
For now I've mashed up the two in this :
![razor](https://cloud.githubusercontent.com/assets/7602755/23834442/f2d09eac-0756-11e7-923a-284df2684001.png)

**Comment by JaimeStill** [comment]
If it helps, here are the icons used in Visual Studio 2017. It's a document with an @ symbol in it:  

**Add New Item**  
![cshtml-template-icon](http://i.imgur.com/zwAnZiz.png)  

**Solution Explorer Icon**  
![cshtml-icon](http://i.imgur.com/MyykOmc.png)

**Comment by LaurentTreguier** [comment]
Then how about something like this ?
![razor](https://cloud.githubusercontent.com/assets/7602755/23834535/395e1d9e-0758-11e7-925c-e8948f67d890.png)

**Comment by JaimeStill** [comment]
Should it have the Angular shield in the background though, being exclusive to ASP.NET MVC? What about something like your `.csproj` or `.json` icons with the @ in it?  

![vs-code-icons](http://i.imgur.com/2SKHqw5.png)

**Comment by LaurentTreguier** [comment]
I thought the HTML background was relevant since razor files seem to be HTML with integrated C# code. I generally use the "generic colored file" background for files that contain data rather than code, like for JSON, XML or text files

**Comment by JaimeStill** [comment]
You're right, sorry! Got them mixed up. That works as well. Thanks a ton for your quick feedback and support!

**Comment by LaurentTreguier** [comment]
You're welcome 😄
